### ISSUE TITLE
Widgets don't enter drag mode until they are moved.

### ISSUE THREAD

**Issue by dkanada** [OpenLauncherTeam/openlauncher#115]
Apps and other items enter drag mode after a long press but widgets don't until you move them a little bit, I looked into this but didn't see any issues with the code. We might want to move WidgetView into AppItemView and just rename it to ItemView, although I haven't looked through the code so I am not sure if that's feasible yet.

**Comment by BennyKok** [comment]
Ha

**Comment by aabaker** [comment]
I have sometimes observed widgets being deleted if they are given a long press but not moved. I suspect this is a related issue.

**Comment by cvigano** [comment]
@aabaker I can reproduce this with 0.5.0 from F-Droid. AntennaPod widget is deleted after long press, widget enters drag mode only if wiggled a bit up and down during the long press.

What is the desired behaviour here? Enter drag mode directly on long press like apps and other items or is the "wiggeling" needed intentional?

**Comment by dkanada** [comment]
They should be functioning the exact same as other items on the desktop as far as I can tell, this is definitely a bug.
