### ISSUE TITLE
Request: add support for screen rotation

### ISSUE THREAD

**Issue by csolisr** [OpenLauncherTeam/openlauncher#120]
By default, the launcher is locked to the default orientation of the device and it can't be changed. I would like to request adding the option to automatically change the orientation depending on the device's rotation (horizontal when the screen is horizontal, vertical when the screen is vertical).

**Comment by dkanada** [comment]
@BennyKok we could handle this with yet another check in the home activity. I removed the settings for landscape columns and rows in the app drawer because it might work to simply reverse the logic and use rows for columns and vice versa, which would be fine for the AppDrawer. I already implemented this in the code so that should work fine when landscape is enabled. I haven't yet figured out a nice way to rotate the desktop, maybe looking at other launchers would help, not sure how they do it.

@csolisr what do you think we should do with the dock and search bar on smaller screens? On tablets the layout would probably be fine if we flip the columns and rows or just leave everything alone since there will be enough space.

**Comment by csolisr** [comment]
@BennyKok @dkanada The default launcher for LineageOS moves the dock to the side, in a vertical fashion, and the search bar becomes a search icon oriented to the other side. [An image of an earlier version for reference.](https://linuxundich.de/wp-content/uploads/2012/12/android_landscape_mode-475x267.png) Rows and columns may be flipped, but I haven't tested it myself because I usually have a single widget on the home screen.

**Comment by ShapeShifter499** [comment]
I would like to see this feature. My device, Nook HD, has an odd rotation issue that isn't easy to solve. The default position is to hold the tablet with the home button upside down. Having rotation support like other android apps and services would help as a workaround.

**Comment by samansalamat** [comment]
could u plz tell me which version had landscape mode?
i really need it.

**Comment by BennyKok** [comment]
It isn't there right now, plz, it takes times and we are not always free to
work in this project.

**Comment by axet** [comment]
This should be a enabled by default for tablets. Thanks!

**Comment by BennyKok** [comment]
Sorry, I have no time at all for this project, as the normal school day started again.  Sorry, you guys have to wait. As I only have a desktop at home,  but when I come back home everyday, it is already night time, so I have no time at all.
