### ISSUE TITLE
When changing a label, new value is not displayed until app restart

### ISSUE THREAD

**Issue by aabaker** [OpenLauncherTeam/openlauncher#139]
If the label for an Item is modified using the Edit option then the new value isn't displayed immediately.

**Comment by dkanada** [comment]
Yeah, right now the drag event doesn't send the item view with it so I can't easily modify it. I have been thinking of the best way to implement this so that eventually it can be implemented in other areas as well, adding a getItemView() method in home right under getCurrentPage() is my current favorite.

**Comment by dkanada** [comment]
fixed
