### ISSUE TITLE
How to translate the app?

### ISSUE THREAD

**Issue by akkk33** [OpenLauncherTeam/openlauncher#142]
## First of all, Thanks for that promising, awesome launcher.
I'd like to contribute by translating it to my language.
How to do that ?

**Comment by dkanada** [comment]
You can edit [this](https://github.com/OpenLauncherTeam/openlauncher/blob/5de5604de414c826300b5d9a578454d464af34bb/app/src/main/res/values/strings.xml) file to add your language. See [here](https://github.com/OpenLauncherTeam/openlauncher/blob/5de5604de414c826300b5d9a578454d464af34bb/app/src/main/res/values-fr/strings.xml) for an example, it is the French translation. It is in a new folder called values-fr since that is the french language code, and the strings tagged with "translatable=false" have been removed.

**Comment by gsantner** [comment]
Even better: Use Stringlate to translate the app. You can do that directly on your android phone. You can get the app e.g. on F-Droid: <https://f-droid.org/repository/browse/?fdfilter=stringlate&fdid=io.github.lonamiwebs.stringlate>

**Comment by akkk33** [comment]
Thanks, I'll provide Arabic translation later today :)
