### ISSUE TITLE
0.5.1 ignores labels setting for desktop, desktop icons never have labels

### ISSUE THREAD

**Issue by sp-1234** [OpenLauncherTeam/openlauncher#150]
That's pretty much it.
I tried changing this setting back and forth several times, desktop icons are always without labels.

App drawer is not affected, labels show up normally in app drawer.

Installed 0.5.1 from F-Droid as an update over 0.4.0 (also from F-Droid). Did not erase anything manually.
Nexus 5X, latest firmware from Google.

**Comment by gsantner** [comment]
Does this also happen to new itmes placed on desktop?

This may be related to the `edit labels on desktop` feature the team is currently working on

**Comment by zeehio** [comment]
As @gsantner suggests, this looks like a migration issue. If you remove the desktop icon and add it again it works fine.

I am also affected by this issue, going from `0.4.x (or before) -> 0.5.0 -> 0.5.1`, updating through fdroid . I always had "Show desktop labels" on, and since 0.5.1 the labels of icons placed with previous openlauncher versions do not appear anymore.

**Comment by sp-1234** [comment]
@gsantner newly added items are displayed OK. Your suggestion was right,
