### ISSUE TITLE
Add a round icon theme on android 7.1+

### ISSUE THREAD

**Issue by mueller-ma** [OpenLauncherTeam/openlauncher#184]
#### General information

* **Device:**   Oneplus X
* **Android Version:**  Android 7.1.2
* **App version:**  0.5.3

#### Steps to reproduce

1. Go to settings
2. Icons
3. Open icon theme dialog

#### Expected result
**What is the expected output?** 
See a default and a round icon theme

**What do you see instead?**
Only a default

**Comment by conrad-heimbold** [comment]
- This would better be implemented in a **separate specialised app**, I think. Just scaling the normal app icons down, so that they fit into a circle used as icon background image, won't look good on low-density / small smartphone screens. 
- Apart from that, I think it only looks good for apps that **already have a curved shape**. File manager (Amaze), E-mail (Default) or Calendar (Etar) App icons, which are rectangular, would probably look strange. 
- dkanada, ikocevski, 1C3 and me (part of the openlauncher team) have made a separate app called ICEcons fork (  ) with **lots of round icons**.  Check it out!

**Comment by mueller-ma** [comment]
I thought about the circle icons which are deliverd by the app:
https://developer.android.com/about/versions/nougat/android-7.1.html#circular-icons

**Comment by conrad-heimbold** [comment]
OpenLauncher wants to be **backwards-compatible** _before_ Android 7.1+; so if that functionality is only available on Android 7.1+; it probably **won't implement it**. _I am sorry._

**Comment by BennyKok** [comment]
ah......
