### ISSUE TITLE
Two graphical issues

### ISSUE THREAD

**Issue by barghest** [OpenLauncherTeam/openlauncher#221]
#### General information

* **App version: 0.5.3 (24) (from F-Droid)**
* **Android Version: LineageOS 11 (4.4.4)**

Hey,
thank you for that nice open source launcher.
Currently I only have two graphical issues:

1. I always have a small white square on the top of the screen (in the middle). It's visible on the desktop and in the drawer. Is there a way to remove it?
2. All icons are sharp but the icon for the app drawer on the desktop looks very blurred. Is there way to get a version that is sharper?

![screenshot_2017-08-17-21-30-56](https://user-images.githubusercontent.com/84884/29430141-93d25968-8393-11e7-855b-99c6956b84c9.png)
![screenshot_2017-08-17-21-30-49](https://user-images.githubusercontent.com/84884/29430140-93cf455c-8393-11e7-86f7-f6be4ee2573b.png)

TIA

**Comment by BennyKok** [comment]
I have no idea at all.....

**Comment by dkanada** [comment]
I am guessing this is because you are on an old version of Android, we might be able to fix the low resolution home button by converting it to an image. @barghest could you try going into the settings and turning off the search bar on the desktop? If that doesn't remove the white square then try turning off either the desktop indicator or the app drawer indicator. Maybe one of those views isn't properly formatted for lower versions of Android.

**Comment by Macchiarch** [comment]
I think that the white square is the "X Remove" square, because when you move and release a widget the "X Remove" square become the small white square and the it disappear.

**Comment by samansalamat** [comment]
is there anyway to convert .png to svg?

**Comment by ildar** [comment]
Yes, namely vectorization

**Comment by gsantner** [comment]
Closing as inactive (OR done) - reopen/comment if needed or if this is still happening

**Comment by ildar** [comment]
@barghest , the issue #2: the icons are scaled. Set scaling to 100%
