### ISSUE TITLE
Support for "Work Profile" apps

### ISSUE THREAD

**Issue by Kazade** [OpenLauncherTeam/openlauncher#282]
#### General information

* **App version: 0.5.5**
* **Android Version: 8.0.0**

#### Expected result
**What is expected?** 

If you have a work profile enabled; on the default Pixel Launcher you get copies of Gmail, Drive etc. with suitcase icons these launch isolated versions of those apps locked to the work profile account. These icons aren't visible in the OpenLauncher launcher - they should be, or there should be a way to switch between profiles in the app listing.

**What does happen instead?**

Only the standard Google apps are listed and there's no apparent way to launch Gmail etc. with the work profile.

#### Steps to reproduce
* Enable a work profile (might have to be done through Device Policy? it happened automatically for me)
* Notice that you can't launch any apps with the work profile.

**Comment by ildar** [comment]
What ROM is that? I wonder if some vendor implemented profiles as Cyanogen
did.

**Comment by Kazade** [comment]
It's the default firmware on the Pixel 2

**Comment by ildar** [comment]
Hm. Found this on the topic:
http://www.verizonenterprise.com/products/mobility/devices/google/
Still are there technical articles on how it works?

**Comment by Kazade** [comment]
Maybe this?

https://developer.android.com/work/managed-profiles.html

**Comment by Kazade** [comment]
Aha! 4th paragraph here: https://developer.android.com/about/versions/android-5.0.html#Enterprise

```If you are developing a Launcher app, you can use the new LauncherApps class to get a list of launchable activities for the current user and any associated managed profiles. Your Launcher can make the managed apps visually prominent by appending a work badge to the icon drawable. To retrieve the badged icon, call getUserBadgedIcon().```

**Comment by serebryakov-av** [comment]
I am using https://play.google.com/store/apps/details?id=com.oasisfeng.island for that. But I also want ability to put work icons to that laucher.

**Comment by serebryakov-av** [comment]
@dkanada Could you help me where I should start discover the project to get know how to implement that feature? I do want it in this launcher! I'll try to learn how implement this feature 8)

**Comment by dkanada** [comment]
Sure! [Here](https://developer.android.com/reference/android/content/pm/LauncherApps) is the relevant code you would need to call to include any work profile apps. The section @Kazade linked above about the [change](https://developer.android.com/about/versions/android-5.0.html#Enterprise) was also helpful. The best place to add this would probably be the [AppManager](https://github.com/OpenLauncherTeam/openlauncher/blob/master/app/src/main/java/com/benny/openlauncher/util/AppManager.java), which serves up the list of available apps to all other areas of the launcher.

I am not sure yet if that class just serves back work profile apps or if it returns all apps, so you may have to do some filtering of the results. Also, since it was introduced in 5.0 there may be some compatibility issues with older versions of Android we need to account for, but Android Studio will throw an error if you call any methods that won't work on older phones. I'll have to do some more digging.

**Comment by shawn1thompson** [comment]
I'm trying to use Open Launcher with Shelter which is also on F-Droid. Maybe some help can be had there?
