### ISSUE TITLE
Search not working when turns off.

### ISSUE THREAD

**Issue by TonSilver** [OpenLauncherTeam/openlauncher#419]
1. Turn off "Search" as a widget in setting.
2. Call it from side-bar.

Error: List will be empty.

**Comment by hummer010** [comment]
Same.

I have set to the Swipe-up gesture, and turned off as a widget.  Search is empty when called.

**Comment by gsantner** [comment]
OK so you turn off search in settings, and then expect it to work? 😄

**Comment by krumelmonster** [comment]
I don't see how this is not a bug. I don't want to have the date and search icon on every desktop (in fact, I don't like it at all) but disabling it in the settings breaks the "search" action: Activating the search action via gesture will darken the screen and open the onscreen keyboard but searching is not possible.

Expected behavior: Activating the search action lets me search regardless of whether the search icon is shown on the desktop.
