### ISSUE TITLE
Displaying values for sliders.

### ISSUE THREAD

**Issue by serebryakov-av** [OpenLauncherTeam/openlauncher#427]
Hi, @dkanada! I tried to find you on Matrix, but I couldn't do it. Therefore I write here =)

I noticed that you refactored Preferences) Good! But also I noticed that sliders now don't display their value. I tried to add it but got some troubles:
- SeekBarPreference is from android.support.v7.preference.
- All code build without supporting v7.
- So I couldn't get a value from SeekBarPreference.

**How to do that?**

p.s. If I try move to android.support.v7.preference all Preference then ColorPickerPreference couldn't be used. It is developed without android.support.v7.preference.

p.p.s. May be [Telegram](https://telegram.org)?

**Comment by serebryakov-av** [comment]
I found a way to get the value!
`Setup.appSettings().getDesktopColumnCount()` for example =)
Is it correct?

Could I use something like:
`preferenceColumns.setOnPreferenceChangeListener(new Preference.OnPreferenceChangeListener() {
    @Override
    public boolean onPreferenceChange(Preference preference, Object newValue) {
        final int progress = Integer.valueOf(String.valueOf(newValue));
        preference.setSummary(String.format("%d", progress));
        return true;
    }
});`

to update value every time slider slides?

**Comment by serebryakov-av** [comment]
p.s. I feel like a beginned developer ^_^

**Comment by dkanada** [comment]
I actually have my own matrix server, if you let me know your username I will message you on Matrix if you would rather chat there!

Yeah, unfortunately none of the color pickers I found supported v7 Preferences, but I was just going to ignore that since moving to v7 isn't truly required yet. I was eventually going to port the color preference to v7 myself if I had time. For the seekbar, I was actually thinking a custom SeekBarPreference would work best so we could style it ourselves. It would also avoid calling `Setup.appSettings().getDesktopColumnCount()` too often and we could simply get the current value of the seekbar from the preference. We could also just use [this](https://github.com/woxingxiao/BubbleSeekBar) library, which looks quite nice.

**Comment by serebryakov-av** [comment]
I thought about custom slider too! I may do it this weekend :)

My nickname is @tonsilver:matrix.org
