### ISSUE TITLE
Bug. PrimaryColored main screen.

### ISSUE THREAD

**Issue by serebryakov-av** [OpenLauncherTeam/openlauncher#433]
@dkanada, something went wrong on commit 967e22208fd8d16b968a2c3710e7d30c9b8305cc:
![device-2018-10-20-230029](https://user-images.githubusercontent.com/443680/47260031-33097c80-d4bc-11e8-8095-3b42a0e7c409.png)

Whole screen now is painted with `primaryColor`.

p.s. My phone: ONEPLUS 2000, Android 8.1.0, Oxygen 5.1.3.

**Comment by dkanada** [comment]
Oh man, this is why we test things. Most likely reason is that at some point your phone is setting the StatusFrame or NavigationFrame to 0dp height, which breaks the ConstraintLayout. This is odd because it looks fine on my phone and I have a similar version of Android, which might have been the issue. I have to find a better way to set the status and navigation frame height today anyways, the solution right now was at best a first attempt to get it working.

**Comment by dkanada** [comment]
The previous method was to manually set the bottom and top margin for each element depending on whether or not the Dock or SearchBar views were enabled. The hope is to remove all that code and simply have two bars at the top and bottom that fill the negative space under the system bars.

**Comment by serebryakov-av** [comment]
After a7f7cec8677d8f2f6cbd525dea2bcd1cfc1ad612 all became good :)
