### ISSUE TITLE
Alllow to customize single icon (no pack)

### ISSUE THREAD

**Issue by Stupidman22** [OpenLauncherTeam/openlauncher#498]
Hi bro, i'm very like your launcher.
But can you make feature to change icon by hand. i want to manualy change it. That is one of the most customize feature if have.
Thank you

**Comment by dkanada** [comment]
As long as the code looks good I'd love to merge it! Custom icons will require a lot of changes though, so please open a pull request if you're working on it so I can review it over time rather than all at once.

1. changes to [IconPackHelper](https://github.com/OpenLauncherTeam/openlauncher/blob/master/app/src/main/java/com/benny/openlauncher/util/IconPackHelper.java) to support applying a single icon
2. update [EditItemListener](https://github.com/OpenLauncherTeam/openlauncher/blob/master/app/src/main/java/com/benny/openlauncher/viewutil/DialogHelper.java#L189) to support more than just the label
3. add new column in [DatabaseHelper](https://github.com/OpenLauncherTeam/openlauncher/blob/master/app/src/main/java/com/benny/openlauncher/util/DatabaseHelper.java) to support custom icons
4. find a good place to apply the custom icons
5. custom activity to pick an icon from any installed pack

The installed apps themselves aren't currently tracked in the database (only items on the desktop are tracked) so you would need to modify the database to track installed apps if you wanted full support for custom icons. It might even be better to submit more than one pull request. After listing out all the required changes I remembered why I haven't done the work myself yet.

**Comment by Stupidman22** [comment]
I think we can add new column in database and save URI of customize image. 
The problem is hard when we need to load image view from URI it may take more time to load --> if can have solution to apply Glide to load image will be ok ...

**Comment by dkanada** [comment]
I think we already use the URI for all icon pack images, which is probably extremely slow. If you wanted to move all icon loads to Glide that would be great, the desktop definitely takes a really long time to start at the moment.

**Comment by dkanada** [comment]
I'm closing this issue in favor of #305 since it's the same issue, but I'm looking forward to any progress you can make for custom icons!
