### ISSUE TITLE
Home button doesn't switch to the screen that's defined to be OpenLauncher's "Home"

### ISSUE THREAD

**Issue by just-Nob** [OpenLauncherTeam/openlauncher#501]
#### General Information

* **OpenLauncher Version:** 0.7.0 (38)
* **Android Version:** 8.1 Oreo
* **Custom ROM:** No, BQ Stock ROM (Aquaris X Pro)
* **Install Source:** F-Droid

#### Description

With the new version 0.7.0, Android's "Home" button has only a restricted functionality:
If having another app in foreground, OpenLauncher can be called by a tap on the "Home" button, but it's not possible anymore to call the launcher's "Home" screen using it (neither when calling it out of another app, nor when still having OpenLauncher running in forgetting).

**Comment by FrancoisMz** [comment]
Hello,

Same behaviour here since OpenLauncher 0.7.0
Android: 8.1
Install Source: F-Droid
Device: BQ Aquaris V

**Comment by ectatomma** [comment]
It's happenning as well on Android 7.2.1, OpenLauncher 0.7.0
Install Source: F-Droid
Custom ROM: Yes, Lineage OS
Device: Moto G 2015 Osprey

**Comment by zootboy** [comment]
I've done a bisect to try and track this issue down. It seems to have been introduced in 7150f8225cf8ca. From this commit onward the behavior is partially broken (on my device, it worked when shifting left but not when shifting right).

I'm going to keep digging, but I'm not very familiar with Android coding. If anyone else wants to jump in and help debug this, I'd be grateful.

**Comment by frank-bxl** [comment]
I must confirm the enduring of the bug.
OpenLauncher 0.7.3
/e/OS 0.9-20200514
Device Fairphone 3

**Comment by peterph** [comment]
Just by looking at the code for the first time, I would suggest starting at 
(app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java)[https://github.com/OpenLauncherTeam/openlauncher/commit/7150f8225cf8cac3010e3af5545290c691ec2126#diff-a5c676d803f18e59b5bcb130ab0ab23e]

the code around (line 658)[https://github.com/OpenLauncherTeam/openlauncher/blob/7150f8225cf8cac3010e3af5545290c691ec2126/app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java#L658]:

    else if (getAppDrawerController().getDrawer().getVisibility() == View.VISIBLE)

looks like it may be the culprit - namely the `else if` instead of the original `else` (which is actually missing now)

**Comment by peterph** [comment]
Just by looking at the code for the first time, I would suggest starting at 
(app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java)[https://github.com/OpenLauncherTeam/openlauncher/commit/7150f8225cf8cac3010e3af5545290c691ec2126#diff-a5c676d803f18e59b5bcb130ab0ab23e]

the code around (line 658)[https://github.com/OpenLauncherTeam/openlauncher/blob/7150f8225cf8cac3010e3af5545290c691ec2126/app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java#L658]:

    else if (getAppDrawerController().getDrawer().getVisibility() == View.VISIBLE)

looks like it may be the culprit - namely the `else if` instead of the original `else` (which is actually missing now).

**Comment by peterph** [comment]
Just by looking at the code for the first time, I would suggest starting at 
(app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java)[https://github.com/OpenLauncherTeam/openlauncher/commit/7150f8225cf8cac3010e3af5545290c691ec2126#diff-a5c676d803f18e59b5bcb130ab0ab23e]

the code around (line 658)[https://github.com/OpenLauncherTeam/openlauncher/blob/7150f8225cf8cac3010e3af5545290c691ec2126/app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java#L658]:

    else if (getAppDrawerController().getDrawer().getVisibility() == View.VISIBLE)

looks like it may be the culprit - namely the `else if` instead of the original `else` (which is actually missing now).

**Comment by peterph** [comment]
Just by looking at the code for the first time, I would suggest starting at 
(app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java)[https://github.com/OpenLauncherTeam/openlauncher/commit/7150f8225cf8cac3010e3af5545290c691ec2126#diff-a5c676d803f18e59b5bcb130ab0ab23e]

the code around (line 658)[https://github.com/OpenLauncherTeam/openlauncher/blob/7150f8225cf8cac3010e3af5545290c691ec2126/app/src/main/java/com/benny/openlauncher/activity/HomeActivity.java#L658]:

    else if (getAppDrawerController().getDrawer().getVisibility() == View.VISIBLE)

looks like it may be the culprit - namely the `else if` instead of the original `else` (which is actually missing now).

**Comment by GHolk** [comment]
Hey, I am using the nightly build and discover this fix.
There are some issues in nightly build:

 1. It does not alway switch back to the home page.
    It seem that pressing home key in the leftest page always can not switch back to the home page.

    I always set the center page as the home page but not the leftest one,
    (so I always prefer open launcher to the built-in one QuickStep.)
    and when I press the home key in the leftest page, it will not switch to the center one.

 2. Launch any app or press home key in other apps will both switch to the home page.
    I'm not sure whether this is the expected behavior.

    Personally, I want pressing home key *in other apps* will just back to the launcher and stay in the last page;
    and pressing the home key *in launcher itself* will switch to the home page.

**Comment by just-Nob** [comment]
> Hey, I am using the nightly build and discover this fix.


Hi @GHolk ,

do you compile the nightlies by yourself, or is there an official page where to download compiled APKs?

**Comment by GHolk** [comment]
I just download the apk. I don't know android development.

**Comment by GHolk** [comment]
Hey, I tried the v1.0.0 version, but there is still a bug (as my [comment on May 7](#issuecomment-1537444213))

> Hey, I am using the nightly build and discover this fix. There are some issues in nightly build:
> 
>   1. It does not alway switch back to the home page.
>      It seem that pressing home key in the leftest page always can not switch back to the home page.
>      I always set the center page as the home page but not the leftest one,
>      (so I always prefer open launcher to the built-in one QuickStep.)
>      and when I press the home key in the leftest page, it will not switch to the center one.
> 

If I have 5 pages in OpenLauncher and set the 3rd page as *home page*,
OpenLauncher will not go back to home page
when I press home key at the 1st page (count from left to right).

## workaround
You can just add one additional page at the leftest and do not use it.
If you do not use it, you will never switch to it and want to press home key on it,
and you will not face this bug.

**Comment by GHolk** [comment]
Okay, not only one bug. The second issue I mentioned is not fully fix, too.

When I launch app on OpenLauncher, it always switch to the *home page*.
(you can see tha animation switch to the home page before the app launch)

Close the app drawer also switch to the *home page* too.

**Comment by gsantner** [comment]
OpenLauncher is discontinued. Check README.
