### ISSUE TITLE
App drawer is gone since the last update

### ISSUE THREAD

**Issue by OffifialMITX** [OpenLauncherTeam/openlauncher#61]
(F-Droid) I can't even add it manually anymore.

**Comment by offa** [comment]
Had the same problem, here's my solution:

1. Long press on the desktop (to modify it)
1. Action -> AppDrawer
1. Place it as you need

**Comment by dkanada** [comment]
If the above doesn't work, you might be having the same issue that I am. If you have an item in the top left corner remove it first and then add the app drawer button. It should then appear in the top left corner.

**Comment by BennyKok** [comment]
There is a problem will adding it when the desktop is not empty.

**Comment by aabaker** [comment]
Part of the problem is that onOptionsItemSelected() for the add app drawer method calls addItemToPosition() with x and y coordinates that are cell numbers. Other calls to addItemToPosition() appear to use screen x/y coordinates and the touchPosToCoordinate() method that addItemToPosition() uses expects screen coordinates, not cell numbers.

**Comment by BennyKok** [comment]
@aabaker wow, you did read the code, thanks for the suggestion, I will try to fix this.

**Comment by aabaker** [comment]
Reading the code only got me part way there, I had to run it in the debugger to finish the task.

The other issue I spotted with this code using addItemToPosition is that it seems reasonable to not display an error for the case where the positions are touch coordinates because the user can see that where they touched isn't empty but in this case displaying toast_notenoughspace would seem appropriate.

**Comment by BennyKok** [comment]
Yeah I gonna have to take some times as I am still busy with some of my work.

**Comment by BennyKok** [comment]
Is this problem still happening?

**Comment by aabaker** [comment]
I suspect the app drawer disappearing from the dock was specifically related to upgrading where the code handling IsInvalidate changed so wouldn't re-occur. The problem that once that happened you couldn't recreate the app icon if the top left square was in use is fixed.

**Comment by BennyKok** [comment]
Great, thanks guys.
