### ISSUE TITLE
Restore backup doesn't work after 0.3.2 to 0.3.2.1 update

### ISSUE THREAD

**Issue by urbanomad64** [OpenLauncherTeam/openlauncher#87]
Restore isn't working after updating to version 0.3.2.1 so I have a blank launcher.

**Comment by dkanada** [comment]
We have been making a bunch of changes to the preferences and other saved data recently so that is probably the issue. I just recently moved all of the data from a json file to an SQLite database so the old backups wont work anymore. The next update will move the settings from json to the standard settings library which will break the settings backup, but after that there shouldn't be any more incompatible updates.

**Comment by gsantner** [comment]
We changed much on the backend with 0.4.0 which wil be out soon. There you can't restore old backups, because everything changed drastically. Note that the project is in a alpha state.

Closing as won't fix
