### ISSUE TITLE
Dock set for 5 slots but only accepts 4 v.0.0.4

### ISSUE THREAD

**Issue by urbanomad64** [OpenLauncherTeam/openlauncher#95]
I cannot fill the middle spot in my dock as it gives not enough space error.

**Comment by dkanada** [comment]
This issue is related to the modified action items and will be fixed when the app data is cleared. @BennyKok is there any way to remove the occupied array and just check to see if there is currently a View in the selected cell? If we can't do that maybe we can flag the cell as occupied only after an ItemView has been added to prevent crashes from incorrectly updating the state of a cell.

**Comment by offa** [comment]
Thanks, clearing the app data worked for me.

**Comment by BennyKok** [comment]
@dkanada well currently, there isn't a method to do it, you can implement it like what you said.
